[project]
name = "corpus-te"
version = "0.1.0"
description = "Telugu corpus collections backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "pydantic",
    "python-multipart",
    "alembic"
]
